version: "3"

networks:
    news-app-network:

services:
    news-app1:
        build:
            context: ..
            dockerfile: docker/php-apache/Dockerfile
        container_name: news-app1
        volumes:
            - ./..:/var/www/html
        environment:
            CONTAINER_ROLE: app
        ports:
            - "88:80"
        networks:
            - news-app-network

    news-app-mysql:
        image: mariadb:latest
        # platform: linux/x86_64
        build:
            context: ..
            dockerfile: docker/mysql/Dockerfile
        container_name: news-app-mysql
        volumes:
            - news_app_mysql_data:/var/lib/mysql
        ports:
            - "3316:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=mysqlroot
            - MYSQL_DATABASE=news_apis
        networks:
            - news-app-network

    news-app-supervisor:
        build:
            context: ..
            dockerfile: docker/php-apache/Dockerfile
        container_name: news-app-supervisor
        volumes:
            - ./..:/var/www/html
        environment:
            CONTAINER_ROLE: supervisor
        networks:
            - news-app-network

volumes:
    news_app_mysql_data:
        driver: "local"
